name: Release

on:
  repository_dispatch:
    types: [release]
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  release-pypi:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.11'
          cache: 'true'

      - name: Install dependencies
        run: pdm install

      - name: Run tests
        run: |
          pdm run pbs-install 3.10 -d test1 -v
          version=$(test1/bin/python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
          [[ $version == "3.10" ]] || exit 1

      - name: Run tests with build
        run: |
          pdm run pbs-install 3.10 -d test2 -v --build-dir
          version=$(test2/install/bin/python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
          [[ $version == "3.10" ]] || exit 1

      - name: Upload to Pypi
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          pdm publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
