name: Update the Python versions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: '3.11'
          cache: 'true'
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          pdm install

      - run: pdm run update
        id: update
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Push changes
        if: steps.update.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          tags: true
